language: ruby
sudo: false
cache: bundler
bundler_args: --without sql benchmarks console tools
script: "bundle exec rake ci"
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - rbx-2
  - jruby-9.0.5.0
  - ruby-head
  - jruby-head
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
