language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without sql benchmarks console tools
script: "bundle exec rake ci"
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - rbx-3
  - jruby-9.1.6.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: rbx-3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
