language: ruby
cache: bundler
bundler_args: --without benchmarks console tools
script: "bundle exec rake ci"
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - jruby-9.1.13.0
env:
  global:
    - COVERAGE="true"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
